version: '3'

services:
  postgres:
    image: postgres:14
    container_name: orm-bench-db
    restart: always
    tty: true
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=ormcomparation

volumes:
  db_data: {}